[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--no-audit --no-fund"
  NETLIFY_USE_YARN = "false"
  NETLIFY_IGNORE_TYPESCRIPT_ERRORS = "true"
  VITE_SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"
  VITE_OUTLOOK_CLIENT_ID = "e1bc825c-0baf-4b72-9df7-221003bb2749"
  VITE_OUTLOOK_CLIENT_SECRET = "d67eb5b5-8934-4662-8977-357ead6d7b2b"
  VITE_OUTLOOK_REDIRECT_URI = "https://mailsyncai.netlify.app/auth/provider"
  DEEPSEEK_API_KEY = "sk-9983763537d940c3912078e3d3790dc5"
  SMTP_HOST = "smtp.mailgun.org"
  SMTP_PORT = "587"
  SMTP_USERNAME = "postmaster@mailsyncai.com"
  SMTP_FROM = "noreply@mailsyncai.com"
  SITE_URL = "https://eloquent-parfait-84d32a.netlify.app"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Force HTTPS for all requests
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Minimal security headers to avoid compatibility issues
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:;"

[functions]
  directory = "supabase/functions"

[functions.oauth-exchange]
  included_files = ["supabase/functions/oauth-exchange/*"]

[functions.send-email]
  included_files = ["supabase/functions/send-email/*"]

[functions.email-sync]
  included_files = ["supabase/functions/email-sync/*"]

[functions.email-summary]
  included_files = ["supabase/functions/email-summary/*"]

[functions.oauth-exchange.environment]
  SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"
  GMAIL_CLIENT_ID = "1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com"
  GMAIL_CLIENT_SECRET = "GOCSPX-abcdefghijklmnopqrstuvwxyz"
  OUTLOOK_CLIENT_ID = "e1bc825c-0baf-4b72-9df7-221003bb2749"
  OUTLOOK_CLIENT_SECRET = "d67eb5b5-8934-4662-8977-357ead6d7b2b"
  YAHOO_CLIENT_ID = "dj0yJmk9abcdefghijklmnopqrstuvwxyz"
  YAHOO_CLIENT_SECRET = "abcdefghijklmnopqrstuvwxyz123456"

[functions.send-email.environment]
  SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"
  SMTP_HOST = "smtp.mailgun.org"
  SMTP_PORT = "587"
  SMTP_USERNAME = "postmaster@mailsyncai.com"
  SMTP_FROM = "noreply@mailsyncai.com"
  SITE_URL = "https://mailsyncai.netlify.app"

[functions.email-sync.environment]
  SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"
  OPENAI_API_KEY = "sk-9983763537d940c3912078e3d3790dc5"

[functions.email-summary.environment]
  SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"
  OPENAI_API_KEY = "sk-9983763537d940c3912078e3d3790dc5"

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200 