[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.9.2"
  # Ignore TypeScript errors during build
  NETLIFY_USE_YARN = "false"
  NETLIFY_IGNORE_TYPESCRIPT_ERRORS = "true"
  # Supabase configuration
  VITE_SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  # This is your actual Supabase anon key
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbnhxamd1YXRxcmFveGlkdHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1Mjg3ODgsImV4cCI6MjA1NjEwNDc4OH0.pGFzeld6sKKvaVr6jbvkUUggHotq3XFGfktRXu8wNWo"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 