[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.9.2"
  # Ignore TypeScript errors during build
  NETLIFY_USE_YARN = "false"
  NETLIFY_IGNORE_TYPESCRIPT_ERRORS = "true"
  # Supabase configuration
  VITE_SUPABASE_URL = "https://ucnxqjguatqraoxidtsq.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 